/**
 *	AlarmInterface.java
 *	@author Gaston
 *	The AlarmInterface defines the methods used to interact with an Alarm.
 *
 */

public interface AlarmInterface
{
	/**
	 * The takeNotice method is meant to respond to events associated with,
	 * or actions generated by, an Alarm.
	 */
	public void takeNotice();

}